### ISSUE TITLE
How to setup for my hand?

### ISSUE THREAD

**Issue by ericshermancs** [Shinao/SmartMirror#2]
How do I set up the mirror to work with my hand? How would I find the variables to put in the config file?
Thank you

**Comment by Shinao** [comment]
Launch test.py to debug with a configurable environment

You have to understand that to recognize your hand you first have to make an open palm like shown in the README (It's the command to open the widget menu).
You shouldn't have to tweat the paramsMinMax for your hand to be recognized because it will automatically scroll through the HSV values to get it.
https://gfycat.com/BountifulCanineBushsqueaker : See how it doesn't track my hand before I make a palm ? (it says Search Palm)

If you still want to tweat the paramsMinMax window to get your hand here are some screenshot that shows the difference between a full range and a small range HSV values :
![capture2](https://cloud.githubusercontent.com/assets/3755971/17566474/d02c3d66-5f3b-11e6-8776-acde27e21c1b.PNG)
![capture](https://cloud.githubusercontent.com/assets/3755971/17566475/d02ef664-5f3b-11e6-8579-e547783e446f.PNG)

**Comment by ericshermancs** [comment]
When I type "python test.py", no environment shows on screen, the terminal just hangs on it

**Comment by G10DRAS** [comment]
Hello @Shinao,  After putting 3-4 hours of effort, I managed to configured HSV range. But even after that it hardly recognizing 'PALM' (once in 50 frames).  It say "PALM' but in actual it detect something else and declare it as 'PALM'. 
Is the code in Git working?  Specially "motion.py"

**Comment by Shinao** [comment]
@esazsX I've just pushed a commit for a warning if the camera is not found, this happens when I don't plug my webcam, verify yours. 
Try this code to see if its a camera problem : http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html

@G10DRAS Hey ! First of all, bear with me, It works great in my house and with my hand but I haven't have any negative feedback except yours to make the detection better so if you have a bit of time I will work on it. test.py basically use motion.py and output opencv windows to debug it, it works in my environment.

I also pushed a commit where you can see how my palm detection works, you just have to uncomment this line in test.py : `#motion.debugPalm = True`
It basically scroll through the lightness of the frame to get the hand, you can see the code in motion.py:TryToTrackHand, it's a simple loop.

The only problem that I can guess is if your hand and the background are almost the same color (white hand/white background/full light on) it can be hard to detect it since the hand will merge with your wall.

I will be in holiday for one more week so if you don't want to browse and edit some code you can send me a picture or a video with your open palm and I will see why it's not doing what it's supposed to when I come back.

**Comment by ericshermancs** [comment]
@Shinao , I now see it says no camera found, but I am able to take pictures from it using the raspistill command

**Comment by Shinao** [comment]
@esazsX I probably have something in my environment from my previous projects to make it work... 
If you have the will, you can probably replace the bit of code that read frames (videoDevice at the start of motion.py) to use PiCamera instead. It should be a change of a few lines of code.
See Step 6 for example: http://www.pyimagesearch.com/2015/03/30/accessing-the-raspberry-pi-camera-with-opencv-and-python/
If not, I will get to it when I come back from holiday.

**Comment by ericshermancs** [comment]
OK, thank you very much!

**Comment by G10DRAS** [comment]
@Shinao, I tweak code a bit, make it simple for testing and took only Gesture dectection part out of it. 
I am using a Logicool HD C270 camera with RPi2B (Python 2.7, Raspbian Whizzy, OpenCV 2.x). 
See this, What I am getting all the time (False detection of PALM), I tested it in various light condition but never get a true PALM detected.

![palm](https://cloud.githubusercontent.com/assets/14088095/17609184/32c8274a-6050-11e6-85a8-f3c335037cce.jpg)

**Comment by Shinao** [comment]
@esazsX I pushed a commit that should take care of the pi camera directly. I did not test it since I don't have the hardware on me but it's only a few line of codes in Motion:init and Motion:GetFrameFromVideoDevice. Please follow this tutorial http://www.pyimagesearch.com/2015/03/30/accessing-the-raspberry-pi-camera-with-opencv-and-python/ from Step 4 through Step 5 to install the lib and tweak things if necessary. You also need to set the useRaspberryPiCamera to True in config.py.

@G10DRAS You are tweaking the wrong settings, paramMinMax is only when you want to detect the palm. In your screenshot you have already found it (since it tracks something). What you need to do is increase the paramSearchRange settings, it tells it to increase the range from the HSV point of the center of your palm, your hand have a lot more range of brightness that mine so you have to increase the DEC H/S/V.

**Comment by ottins** [comment]
Hi Shinao, thanks for sharing your project and code! I was trying to use the pi camera as well as esazsX was doing. The code in commit f75f3d7 didn't work for me because the camera was visible (in my case) as /dev/video0 therefore the VideoCapture(0) command in motion.py was making the picamera busy. Adding a "if not config['useRaspberryPiCamera']" before the VideoCapture(0) command solved for me. Some fine tuning was also necessary for me in the IsActive() and Dispose() method.
Finally, let me notice out that in the config.py file, hsv_min_blue and hsv_max_blue paramenter were defined while the motion.py was calling hsv_lower_blue and hsv_upper_blue (I think it's just a typo and I set hsv_min_blue and hsv_max_blue in the motion.py file as well).
After such amendments, the code was able to recognize the palm, I will now try to replicate the gesture reading.
Very nice job, thank you again. 
[motion.py.txt](https://github.com/Shinao/SmartMirror/files/441076/motion.py.txt)

**Comment by Shinao** [comment]
@ottins Thanks a lot for the feedback ! I've pushed the necessary modifications to the project. I also changed a lot of names and added a lot of commentaries to the config.py to be clear who does what.
If you have any problems or questions, don't hesitate to post in here or even email me directly.

**Comment by G10DRAS** [comment]
I guess there is a typo (COLOR_BGR2GRAY) in below code.
motion.py line 80

```
# Get frame difference to avoid doing things when there is no movement
self.frameDifference = cv2.absdiff(cv2.cvtColor(Motion.currentFrame, cv2.COLOR_RGB2GRAY), cv2.cvtColor(Motion .previousFrame, cv2.COLOR_BGR2GRAY))
```

**Comment by Shinao** [comment]
Dunno why there is both is OpenCV : 

> COLOR_BGR2GRAY : convert between RGB/BGR and grayscale, color conversions
> COLOR_RGB2GRAY : ''

Changed it anyway, seems like it works the same. Thanks

**Comment by G10DRAS** [comment]
Under gesture.py, funtion CheckForThumbs() is calculating few ratios, seems they all are integer calculations while they need to return float value.
I haven't tested the full code yet, but looks like code needs some improvment.

**Comment by Shinao** [comment]
@G10DRAS I don't understand what you mean, I even have a debug line commented out in this section and it prints : `Ratio: 0.1259259259259259`
After some research I found that it's the default behavior in python 3 (integer division becomes float) but not in python 2... great. I don't want to mess up my environment - if you want to make the modifications so that it will work with python 2 go for it I will gladly accept some PRs.

**Comment by G10DRAS** [comment]
Thats what my first question on hackster.
https://www.hackster.io/user0786116/smartmirror-553ecc

Well its clear now why the code was not working for me out of the box.

**Comment by mainframe2017** [comment]
Hello Team

I found issue shown in snapshot.

![capturejj](https://cloud.githubusercontent.com/assets/25217920/23501871/b7bc3f40-ff5b-11e6-9aa2-024e82fcb866.PNG)

Thank you

**Comment by Shinao** [comment]
http://stackoverflow.com/questions/25504964/opencv-python-valueerror-too-many-values-to-unpack
http://stackoverflow.com/questions/30924665/valueerror-too-many-values-to-unpack-python-2-7

You have the opposite error of these guys. You must have a version of OpenCV where the function findContours returns 2 values instead of 3.
To make it work you should probably remove the first underscore and comma at gesture.py:101

You might consider updating OpenCV to a more recent version.

**Comment by mainframe2017** [comment]
Find another issue.

![capturejj](https://cloud.githubusercontent.com/assets/25217920/23502749/e8c94148-ff5e-11e6-8a71-a53c0026d4d1.PNG)

**Comment by Shinao** [comment]
You should learn a bit of python to fix errors like this.
Python has a strict indentation (spaces and tabulation) policy. By removing the underscore you probably added a space or something.
Also be careful what editor you use on linux, my experience is that sometimes they replace spacing with whatever they like best.

**Comment by mainframe2017** [comment]
i resolve it 

Thank you Team

**Comment by mainframe2017** [comment]
another error in gesture detection.
![capturejj](https://cloud.githubusercontent.com/assets/25217920/23504517/d4ccd298-ff65-11e6-8a55-931237ffb8f0.PNG)

**Comment by Shinao** [comment]
Please read the README. You have to launch the node server for it to receive the gestures.
But even with these messages you can still test it. At least a window should popup with the webcam feed.

**Comment by mainframe2017** [comment]
please help me out on this issue.
![capturejj](https://cloud.githubusercontent.com/assets/25217920/23585085/24ef7308-019a-11e7-92eb-5f9dc4056dca.PNG)

**Comment by Shinao** [comment]
Again, unexpected indent.
You added the line framerate in motion.py since it doesn't exist on my file and you must have forgot what I said 3 days ago :

> You should learn a bit of python to fix errors like this.
> Python has a strict indentation (spaces and tabulation) policy. By removing the underscore you probably added a space or something.
> Also be careful what editor you use on linux, my experience is that sometimes they replace spacing with whatever they like best. 

You are commenting on a closed thread which also has nothing to do with the hand configuration.
You use the thread you created a few days ago, I'm locking this one.
